/**
 * Local Quran text, bundled with the app.
 *
 * The four editions live in `public/quran/` as `{ "surahNumber": [verse, ...] }`
 * and are generated by `scripts/build-quran-data.py`. They are fetched lazily —
 * once per edition per session — and memoised, so the whole Quran is readable
 * with no network after the service worker has cached them.
 *
 * The previous approach fetched every surah from api.alquran.cloud on demand and
 * cached it in localStorage, which meant nothing worked offline until you had
 * already opened that surah, and the ~5 MB localStorage ceiling forced an
 * eviction hack. This replaces the network with the bundle; the API is now only
 * a fallback.
 */

export type EditionKey = "arabic" | "en" | "bn" | "translit";

type EditionData = Record<string, string[]>;

const FILES: Record<EditionKey, string> = {
  arabic: "/quran/quran-arabic.json",
  en: "/quran/quran-en.json",
  bn: "/quran/quran-bn.json",
  translit: "/quran/quran-translit.json",
};

const cache = new Map<EditionKey, EditionData>();
const inflight = new Map<EditionKey, Promise<EditionData>>();

/** Load one edition, reusing an in-flight request if one is already running. */
export function loadEdition(edition: EditionKey): Promise<EditionData> {
  const hit = cache.get(edition);
  if (hit) return Promise.resolve(hit);

  const running = inflight.get(edition);
  if (running) return running;

  const request = fetch(FILES[edition])
    .then((res) => {
      if (!res.ok) throw new Error(`${FILES[edition]} -> HTTP ${res.status}`);
      return res.json() as Promise<EditionData>;
    })
    .then((data) => {
      cache.set(edition, data);
      inflight.delete(edition);
      return data;
    })
    .catch((err) => {
      inflight.delete(edition);
      throw err;
    });

  inflight.set(edition, request);
  return request;
}

/** Load every edition the reader needs, in parallel. */
export function loadAllEditions(): Promise<Record<EditionKey, EditionData>> {
  const keys = Object.keys(FILES) as EditionKey[];
  return Promise.all(keys.map(loadEdition)).then((loaded) =>
    Object.fromEntries(keys.map((k, i) => [k, loaded[i]])) as Record<EditionKey, EditionData>
  );
}

/** True once an edition is in memory — lets callers avoid an await on the hot path. */
export function isEditionLoaded(edition: EditionKey): boolean {
  return cache.has(edition);
}

/** Verses of one surah in one edition, or null if not loaded / out of range. */
export function getVerses(edition: EditionKey, surahId: number): string[] | null {
  return cache.get(edition)?.[String(surahId)] ?? null;
}
